adds additional vdi disk for machines and bash aliases
Signed-off-by: Marcel Grosshans <mvg82@gmx.net>

diff --git a/stretch64/Vagrantfile b/stretch64/Vagrantfile
--- a/stretch64/Vagrantfile
+++ b/stretch64/Vagrantfile
@@ -1,6 +1,8 @@
 # -*- mode: ruby -*-
 # vi: set ft=ruby :
 
+second_disk = '../data.vdi'
+
 # All Vagrant configuration is done below. The "2" in Vagrant.configure
 # configures the configuration version (we support older styles for
 # backwards compatibility). Please don't change it unless you know what
@@ -37,7 +39,7 @@ Vagrant.configure("2") do |config|
   # the path on the host to the actual folder. The second argument is
   # the path on the guest to mount the folder. And the optional third
   # argument is a set of non-required options.
-  # config.vm.synced_folder "../data", "/vagrant_data"
+  config.vm.synced_folder "../share", "/share"
 
   # Provider-specific configuration so you can fine-tune various
   # backing providers for Vagrant. These expose provider-specific options.
@@ -59,8 +61,12 @@ Vagrant.configure("2") do |config|
         vb.customize ["storagectl", :id, "--name", "IDE Controller", "--add", "ide"]
      end
      vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso"]
+     unless File.exist?(second_disk)
+         vb.customize ['createhd', '--filename', second_disk, '--size', 100 * 1024]
+     end
+     vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', second_disk]
   end
- 
+
   # View the documentation for the provider you are using for more
   # information on available options.
 
@@ -80,14 +86,22 @@ Vagrant.configure("2") do |config|
      adduser --disabled-password --gecos "" marcel
      echo "marcel:start" | chpasswd
      adduser marcel sudo
+     cp /vagrant/.bash_aliases /home/marcel
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get upgrade -y
      apt-get install -y linux-headers-generic
-     apt-get install -y xinit x11-xserver-utils lxterminal openbox slim 
+     apt-get install -y xinit x11-xserver-utils lxterminal openbox slim
      apt-get install -y build-essential vim-gtk git gitk mutt dillo
+     apt-get install -y libncurses5-dev gcc-arm-linux-gnueabihf bc lzop
      mount /dev/cdrom /mnt
      yes | /mnt/VBoxLinuxAdditions.run
+     if ! [ -e /dev/sdb1 ]; then
+         echo ",,L" | sfdisk /dev/sdb
+     mkfs.ext4 /dev/sdb1
+     fi
+     mkdir /data
+     echo "/dev/sdb1    /data           ext4        errors=remount-ro 0       1" >> /etc/fstab
      reboot
   SHELL
 end
